### ISSUE TITLE
Can't locate symbol in libnumaprof-pintool.so

### ISSUE THREAD

**Issue by Dr-Noob** [memtt/numaprof#26]
I've compiled numaprof as README.md says but (it's installed at /usr/local/lib/) I can't get it to work:

```
[user@drnoob build]$ /usr/local/bin/numaprof -- /bin/ls
E: Unable to load /usr/local/lib/libnumaprof-pintool.so: dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t" referenced by "/usr/local/lib/libnumaprof-pintool.so"...
```
Funny thing is:

```
[user@drnoob build]$ nm -g /usr/local/lib/libnumaprof-pintool.so | grep "_ZnwmSt11align_val_t"
U _ZnwmSt11align_val_t
```
I've already seen #25, however it seems this is a different issue. I'm using ArchLinux, with gcc 8.2.1.

**Comment by svalat** [comment]
This should be fixed by support of last version of pintool.

**Comment by xzx0805** [comment]
@Dr-Noob Hello, I have also encountered the same issue. Did you resolve it?

**Comment by svalat** [comment]
Hi,
you get it on which Linux version with which version of Pintool ?

In 2019 the issue was fixed by an update of pintool on their side.

**Comment by xzx0805** [comment]
@svalat Hi，I've currently tried ubuntu22 with pintool3.28 and ubuntu16.04 with pintool3.5 and they all show the same error：

> dlopen failed: cannot locate symbol "_ZnwmSt11align_val_t" referenced by "/usr/local/lib/libnumaprof-pintool.so"...
