### ISSUE TITLE
1.1.3 release file NPM dependency?

### ISSUE THREAD

**Issue by hpcpony** [memtt/numaprof#41]
I took the release file (.tar.bz2) as opposed to the source file (.tar.gz), but it still seems to have an NPM dependency?
If I try using the "source" (which is really the tar.gz version?) things are much worse.  I'm confused.  which "official tar.gz" should I be downloading?

```
[numaprof]$ md5sum numaprof-1.1.3.tar.bz2
bdf4868c175e6a175daf89f7563feac2  numaprof-1.1.3.tar.bz2
[numaprof]$ tar xaf numaprof-1.1.3.tar.bz2
[numaprof]$ cd numaprof-1.1.3
/home/sadm/numaprof/numaprof-1.1.3
[numaprof-1.1.3]$ mkdir build && cd build
/home/sadm/numaprof/numaprof-1.1.3/build
[build]$ ../configure --prefix=/opt/numaprof-1.1.3 --with-pintool=/opt/numaprof-1.1.3/pin-3.24-98612-g6bd5931f2-gcc-linux
>>> cmake "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=/opt/numaprof-1.1.3" "-DPINTOOL_PREFIX=/opt/numaprof-1.1.3/pin-3.24-98612-g6bd5931f2-gcc-linux" ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using -std=c++11
-- QT5 webkit not found, skip QT5 view
-- Found Numactl: /lib64/libnuma.so  
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found Pintool: /opt/numaprof-1.1.3/pin-3.24-98612-g6bd5931f2-gcc-linux/pin  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Cannot find NPM.  This is required beause you took the git master branch.
  Download official tar.gz or disable webview.  (missing: NPM_BINARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNpm.cmake:14 (find_package_handle_standard_args)
  src/webview/CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/sadm/numaprof/numaprof-1.1.3/build/CMakeFiles/CMakeOutput.log".
```

**Comment by svalat** [comment]
Hi,
Ok, I see the issues, there is some wrong paths in my `CMakeLists.txt` and I never tested on a system which doesn't has the tool so never seen the mistake.

Thanks very much for reporting the issue.

I fixed it and made a new release (1.1.4). You need to download the `numaprof-1.1.4.tar.bz2` file which already contains the downloaded external Npm/Pip dependencies. Otherwise you need to have `npm` & `pip` available to download them (if you use git or the github auto-generated sources).

Can I ask you to confirm it is ok on your side to close the ticket ?

**Comment by hpcpony** [comment]
Great!  Thanks for the quick response.  I grabbed 1.1.4 and it built fine; still trying to figure out how to use it. ;^)

I will note that there seemed to be issues with the standard CentOS versions of gcc (4.8.5) and cmake (2.8.12.2) but using gcc/9.3.0 and cmake 3.23.2 worked fine (just in case someone else runs into this).

**Comment by svalat** [comment]
For checking, which version of CentOS are you using ?

**Comment by hpcpony** [comment]
Centos 7

**Comment by svalat** [comment]
In case you need I fixed the Centos7 support (with official cmake & gcc) issue in master branch. I will make a new release when I have confirmation that #40 is fixed.

**Comment by hpcpony** [comment]
I'm ok with 1.1.4. I can deal with using newer tools. Just wanted to
mention it in case others try with centos 7 (to be specitic i think we are
7.9)
